name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Set up sqlc
        uses: sqlc-dev/setup-sqlc@v4
        with:
          sqlc-version: '1.25.0'

      - name: Generate SQL code
        run: sqlc generate --file internal/db/sqlc.yaml

      - name: Lint
        uses: golangci/golangci-lint-action@v6

      - name: Test
        run: go test -race -timeout 30s ./...
